# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree.ui'
#
# Created: Sat Oct 10 15:43:05 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PorxyList(object):
    def setupUi(self, PorxyList):
        PorxyList.setObjectName(_fromUtf8("PorxyList"))
        PorxyList.resize(567, 327)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PorxyList.sizePolicy().hasHeightForWidth())
        PorxyList.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(PorxyList)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 311))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.treeList = QtGui.QTreeWidget(self.tab1)
        self.treeList.setGeometry(QtCore.QRect(0, 0, 561, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.treeList.setFont(font)
        self.treeList.setObjectName(_fromUtf8("treeList"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.treeList.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList.headerItem().setFont(4, font)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.treeList_P = QtGui.QTreeWidget(self.tab2)
        self.treeList_P.setGeometry(QtCore.QRect(0, 0, 561, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.treeList_P.setFont(font)
        self.treeList_P.setObjectName(_fromUtf8("treeList_P"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.treeList_P.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_P.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_P.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_P.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_P.headerItem().setFont(4, font)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.treeList_F = QtGui.QTreeWidget(self.tab3)
        self.treeList_F.setGeometry(QtCore.QRect(0, 0, 561, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.treeList_F.setFont(font)
        self.treeList_F.setObjectName(_fromUtf8("treeList_F"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.treeList_F.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_F.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_F.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_F.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.treeList_F.headerItem().setFont(4, font)
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        PorxyList.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PorxyList)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuProxy_Test = QtGui.QMenu(self.menubar)
        self.menuProxy_Test.setObjectName(_fromUtf8("menuProxy_Test"))
        PorxyList.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuProxy_Test.menuAction())

        self.retranslateUi(PorxyList)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PorxyList)

    def retranslateUi(self, PorxyList):
        PorxyList.setWindowTitle(_translate("PorxyList", "Proxy Tester", None))
        self.treeList.headerItem().setText(0, _translate("PorxyList", "Proxy Type", None))
        self.treeList.headerItem().setText(1, _translate("PorxyList", "Host : Port", None))
        self.treeList.headerItem().setText(2, _translate("PorxyList", "Test Result", None))
        self.treeList.headerItem().setText(3, _translate("PorxyList", "Elapsed Time", None))
        self.treeList.headerItem().setText(4, _translate("PorxyList", "Comments", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("PorxyList", "All Proxy", None))
        self.treeList_P.headerItem().setText(0, _translate("PorxyList", "Proxy Type", None))
        self.treeList_P.headerItem().setText(1, _translate("PorxyList", "Host : Port", None))
        self.treeList_P.headerItem().setText(2, _translate("PorxyList", "Test Result", None))
        self.treeList_P.headerItem().setText(3, _translate("PorxyList", "Elapsed Time", None))
        self.treeList_P.headerItem().setText(4, _translate("PorxyList", "Comments", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("PorxyList", "Passed Proxy", None))
        self.treeList_F.headerItem().setText(0, _translate("PorxyList", "Proxy Type", None))
        self.treeList_F.headerItem().setText(1, _translate("PorxyList", "Host : Port", None))
        self.treeList_F.headerItem().setText(2, _translate("PorxyList", "Test Result", None))
        self.treeList_F.headerItem().setText(3, _translate("PorxyList", "Elapsed Time", None))
        self.treeList_F.headerItem().setText(4, _translate("PorxyList", "Comments", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("PorxyList", "Failed Proxy", None))
        self.menuProxy_Test.setTitle(_translate("PorxyList", "Proxy Test", None))

